[build]
  command = "npm run build"  # Команда для сборки проекта
  publish = "build/"  # Директория, из которой Netlify будет раздавать статические файлы

[functions]  # Если у вас есть серверные функции
  directory = "netlify/functions"

[dev]
  command = "npm run start"  # Команда для запуска проекта в режиме разработки
